Refactoring logging, adding run-parts, remove conf folder, move conf-file next to action/checkip scripts

diff --git a/bin/yadynip b/bin/yadynip
--- a/bin/yadynip
+++ b/bin/yadynip
@@ -32,6 +32,7 @@ etcdir=$installdir/etc/$name
 config=$installdir/etc/$name.conf
 
 # Default values
+verbose=none
 logging=none
 quiet=off
 
@@ -41,67 +42,107 @@ for conf in $config ~/.$name.conf ./$name.conf; do
     fi
 done
 
-checkipdir=$etcdir/checkip.d
-actionsdir=$etcdir/actions.d
 ipcachedir=$sharedir/ipcaches
+[ "$quiet" == "on" ] && verbose=none
 
-function log() {
-    local mode=$1
-    shift;
-    [ -z "$logfile" ] || [ "$logging" == "none" ] && return;
-    [ "$logging" != "debug" ] && mode="";
-    [ "$logging" == "debug" ] && mode="[DEBUG]";
-    echo $(date -R) $mode $* >> $logfile
+## Get run scripts or programs in a directory, do not execute.
+## Similar to run-parts(8)
+function runparts()
+{
+    local dir=$1;
+    local regex='[A-Za-z0-9_\-]+$';
+    local parts
+    [ -n "$2" ] && regex=$2;
+    for f in $(/usr/bin/find $dir -type f -regex $dir'/'$regex | sort); do
+        [ -x "$f" ] || continue;	# Skip, if not executable.
+        parts="$parts $f";
+    done
+    /bin/echo $parts;
 }
-function verbose() {
-    [ "$quiet" != "on" ] && return;
-    echo $*
+
+## Return last IP of given type
+function lastip()
+{
+    local lastip=""
+    [ -n "$1" ] && [ -f "$ipcachedir/$1" ] && \
+        lastip=$(/bin/cat "$ipcachedir/$1");
+    /bin/echo $lastip;
 }
-function verbose_log() {
-    local mode=$1
-    shift;
-    log $mode $*
-    verbose $*
+
+## Log message if required by config.
+function log()
+{
+    local level=$1; shift;
+
+    # If verbose output to console according to selected level
+    # verbose levels: none, verbose or debug
+    if [ "$verbose" != "none" ]; then
+        # $verbose = debug -> output
+        # $level != debug -> output
+        [ "$verbose" == "debug" ] || [ $level != "debug" ] && \
+            /bin/echo "[$name] "$*
+    fi
+
+    # No log file, abort here.
+    [ -z "$logfile" ] && return;
+
+    # If logging output to log-file according to selected level
+    # logging levels: none, verbose or debug
+    if [ "$logging" != "none" ]; then
+        # $logging = debug -> output
+        # $level != debug -> output
+        [ "$logging" == "debug" ] || [ $level != "debug" ] && \
+            /bin/echo $(date -R)": "$* >> $logfile
+    fi
+}
+
+## Log a logfile content if required by config.
+function logfile()
+{
+    local now=$(date -R)
+
+    # No log file, abort here.
+    [ -z "$logfile" ] && return;
+    [ "$logging" == "debug" ] || return;
+
+    /bin/sed 's/^/'"$(date -R)"': /' $1 >> $logfile
 }
 
 ## Get my WAN IP address using available checkip scripts
 wanip=
-for f in $checkipdir/* 99ignore~; do
-    # Skip backup file and folder
-    [ -d $f ] && continue
-    echo $f | grep -Pqe "~$" && continue
-
-    # Get my WAN IP
-    wanip=$($f)
-    verbose_log debug $f returns $wanip;
-
-    # Stop here if an IP address is found
-    test -n "$wanip" && break
+for part in $(runparts $etcdir/checkip.d); do
+    log debug Running $part
+    wanip=$($part)
+    [ -n "$wanip" ] && break;
 done
 
 ## Stop here if no WAN IP Address is found
-test -z "$wanip" && echo "$name: No WAN IP Address found" && exit;
+[ -z "$wanip" ] && log debug "No WAN IP Address found" && exit;
 
-verbose_log verbose "WAN IP Address= " $wanip
+## Record and log new WAN IP, if applicable.
+lastip=$(lastip $name)
+[ "$wanip" != "$lastip" ] && \
+    log verbose "WAN IP changed: $wanip" && \
+    /bin/echo $wanip > $ipcachedir/$name
 
 ## Perform actions with detected IP address
-for f in $actionsdir/* 99ignore~; do
-    # Skip backup file and folder
-    [ -d $f ] && continue
-    echo $f | grep -Pqe "~$" && continue
-
+for part in $(runparts $etcdir/actions.d); do
     # Get and check last known IP address for this action
-    lastip=
-    ipcache=$ipcachedir/$(basename $f)
-    [ -f $ipcache ] && lastip=$(cat $ipcache)
+    lastip=$(lastip $(basename $part))
 
     # Skip this action if no new IP address
     [ "$lastip" == "$wanip" ] && continue
 
-    # Execute the action(wanip, logfile), abort upon error.
-    log verbose Execute $f $wanip
-    $f $wanip $logfile || continue
+    # Execute the action(wanip), abort upon error.
+    log debug Running $part $wanip
+    log=$(mktemp)
+    $part $wanip > $log	# Log to file (tried to var, but didn't work
+                        # with multi-lines output)
+    status=$?
+    [ -s "$log" ] && logfile $log	# Use log if not empty
+    /bin/rm -f $log
+    [ $status -ne 0 ] && continue
 
     # Update known IP address for this action
-    echo $wanip > $ipcache
+    /bin/echo $wanip > $ipcachedir/$(basename $part)
 done
